// lib/products.js
// Catalogue officiel des produits et intrants des 3 Domaines (Agro · Véto · Services)
// AGRO VÉTO SERVICES CONGO S.A.R.L.U.

export const DOMAINS_FILTER = [
  { id: 'all', label: 'Tous les Domaines', icon: 'Layers' },
  { id: 'veto', label: 'Domaine VÉTO', sub: 'Élevage, Provenderie, Soins', color: '#0284c7' },
  { id: 'agro', label: 'Domaine AGRO', sub: 'Équipements, Bio-Cosmétique, Sols', color: '#84cc16' },
  { id: 'services', label: 'Domaine SERVICES', sub: 'Formations, Audits & Accompagnement', color: '#15803d' },
]

export const PRODUCT_CATEGORIES = [
  { id: 'all', label: 'Toutes Catégories', domain: 'all' },
  { id: 'poussins', label: 'Poussins d\'un Jour', domain: 'veto' },
  { id: 'provenderie', label: 'Provenderie Certifiée', domain: 'veto' },
  { id: 'sante', label: 'Santé & Prophylaxie', domain: 'veto' },
  { id: 'hygiene', label: 'Hygiène & Biosécurité', domain: 'veto' },
  { id: 'materiel', label: 'Matériel d\'Élevage', domain: 'veto' },
  { id: 'agro-equipement', label: 'Équipements Agricoles & Irrigation', domain: 'agro' },
  { id: 'bio-cosmetique', label: 'Bio-Cosmétique & Artisanat', domain: 'agro' },
  { id: 'formations', label: 'Formations Ferme-École', domain: 'services' },
  { id: 'audit-qhse', label: 'Audits & Accompagnement QHSE', domain: 'services' },
]

export const PRODUCTS_CATALOG = [
  // ── DOMAINE VÉTO ──────────────────────────────────────────
  {
    id: "PROD-01",
    name: "Poussins d'un Jour Cobb 500 (Chair)",
    domain: "veto",
    category: "poussins",
    categoryLabel: "Poussins & Reproduction",
    price: 650, // FCFA l'unité
    priceUnit: "FCFA / poussin (carton de 50)",
    minOrder: 50,
    inStock: true,
    badge: "⭐ Le Plus Rentable",
    image: "/images/products/poussins-cobb500.jpg",
    fallbackImage: "/images/products/poussins-cobb500.jpg",
    description: "Poussins d'un jour vigoureux, vaccinés Marek et Newcastle au couvoir. Taux de croissance exceptionnel et indice de conversion alimentaire optimal pour rentabiliser votre élevage de poulets de chair.",
    specs: ["Souche : Cobb 500", "Vaccination : Marek + Newcastle", "Conditionnement : Cartons aérés de 50 sujets", "Taux de viabilité > 98%"],
  },
  {
    id: "PROD-02",
    name: "Poussins Pondeuses Lohmann Brown",
    domain: "veto",
    category: "poussins",
    categoryLabel: "Poussins & Reproduction",
    price: 950,
    priceUnit: "FCFA / sujet (carton de 50)",
    minOrder: 50,
    inStock: true,
    badge: "Ponte Élevée (320 œufs/an)",
    image: "/images/products/pondeuses-lohmann.jpg",
    fallbackImage: "/images/products/pondeuses-lohmann.jpg",
    description: "Poussins femelles de race pondeuse réputée pour sa robustesse tropicale et un pic de ponte prolongé avec une excellente coquille.",
    specs: ["Souche : Lohmann Brown", "Sexage : 99% garanti", "Entrée en ponte : 18-20 semaines", "Calibre d'œufs : Moyen à gros"],
  },
  {
    id: "PROD-03",
    name: "Aliment Volaille Démarrage Haute Énergie (50kg)",
    domain: "veto",
    category: "provenderie",
    categoryLabel: "Provenderie Industrielle",
    price: 21500,
    priceUnit: "FCFA / sac 50kg",
    minOrder: 1,
    inStock: true,
    badge: "Formule Équilibrée",
    image: "/images/products/aliment-demarrage.jpg",
    fallbackImage: "/images/products/aliment-demarrage.jpg",
    description: "Formulation industrielle certifiée riche en protéines brutes (21%) et acides aminés essentiels pour un démarrage vigoureux et une ossature solide de J1 à J21.",
    specs: ["Protéines brutes : 21.5%", "Énergie métabolisable : 3050 kcal/kg", "Poids net : 50 kg", "Contrôlé en laboratoire AVS"],
  },
  {
    id: "PROD-04",
    name: "Aliment Volaille Croissance Performance (50kg)",
    domain: "veto",
    category: "provenderie",
    categoryLabel: "Provenderie Industrielle",
    price: 19800,
    priceUnit: "FCFA / sac 50kg",
    minOrder: 1,
    inStock: true,
    badge: "Croissance Optimale",
    image: "/images/products/aliment-croissance.jpg",
    fallbackImage: "/images/products/aliment-croissance.jpg",
    description: "Aliment complet pour poulets de chair de J22 à J35. Maximise le gain moyen quotidien (GMQ) et optimise le ratio poids/aliment consommé.",
    specs: ["Protéines brutes : 19%", "Granulométrie : Miettes régulières", "Poids net : 50 kg", "Sans hormones ni farines interdites"],
  },
  {
    id: "PROD-05",
    name: "Aliment Volaille Finition & Engraissement (50kg)",
    domain: "veto",
    category: "provenderie",
    categoryLabel: "Provenderie Industrielle",
    price: 18900,
    priceUnit: "FCFA / sac 50kg",
    minOrder: 1,
    inStock: true,
    badge: "Rendement Carcasse",
    image: "/images/products/aliment-finition.jpg",
    fallbackImage: "/images/products/aliment-finition.jpg",
    description: "Formule d'abattage à forte densité énergétique pour un beau persillage, une chair ferme et une saveur authentique sur le marché de Pointe-Noire.",
    specs: ["Protéines brutes : 18%", "Énergie : 3150 kcal/kg", "Poids net : 50 kg", "Période : De J36 à l'abattage"],
  },
  {
    id: "PROD-06",
    name: "Kit Prophylaxie Avicole Sanitaire Complète",
    domain: "veto",
    category: "sante",
    categoryLabel: "Santé Animale & Soins",
    price: 16500,
    priceUnit: "FCFA / kit pour 100 sujets",
    minOrder: 1,
    inStock: true,
    badge: "Recommandé Vétérinaire",
    image: "/images/products/kit-prophylaxie.jpg",
    fallbackImage: "/images/products/kit-prophylaxie.jpg",
    description: "Ensemble tout-en-un comprenant vitamines antistress de démarrage, anticoccidien, antibiotique curatif préventif et calendrier de vaccination établi par le Dr POUTYA.",
    specs: ["Capacité : Traitement pour 100 poulets", "Guide d'administration inclus", "Validation vétérinaire AVS", "Date limite longue"],
  },
  {
    id: "PROD-07",
    name: "Désinfectant Virucide & Bactéricide Puissant (5L)",
    domain: "veto",
    category: "hygiene",
    categoryLabel: "Biosécurité & Hygiène",
    price: 14500,
    priceUnit: "FCFA / bidon 5 litres",
    minOrder: 1,
    inStock: true,
    badge: "Norme HACCP",
    image: "/images/products/desinfectant-5l.jpg",
    fallbackImage: "/images/products/desinfectant-5l.jpg",
    description: "Solution concentrée pour la désinfection intégrale des poulaillers, pédiluves, rotoluves, cages et mangeoires. Efficace contre la grippe aviaire et la maladie de Newcastle.",
    specs: ["Volume : 5 Litres", "Dilution : 1% à 2%", "Spectre : Bactéricide, virucide, fongicide", "Agréé élevages professionnels"],
  },
  {
    id: "PROD-08",
    name: "Mangeoire Automatique Anti-Gaspillage (10kg)",
    domain: "veto",
    category: "materiel",
    categoryLabel: "Équipements d'Élevage",
    price: 6500,
    priceUnit: "FCFA / unité",
    minOrder: 1,
    inStock: true,
    badge: "Plastique Renforcé",
    image: "/images/products/mangeoire-poules.jpg",
    fallbackImage: "/images/products/mangeoire-poules.jpg",
    description: "Mangeoire suspendue robuste avec grille anti-gaspillage intégrée. Réduit les pertes d'aliment de 25% et évite la souillure par les déjections.",
    specs: ["Capacité : 10 kg d'aliment", "Matériau : Plastique polypropylène haute densité", "Entretien : Lavable et désinfectable", "Usage : Chair et ponte"],
  },

  // ── DOMAINE AGRO ──────────────────────────────────────────
  {
    id: "PROD-09",
    name: "Pulvérisateur Dorsal Professionnel à Pression (16L)",
    domain: "agro",
    category: "agro-equipement",
    categoryLabel: "Équipements Agricoles & Matériels",
    price: 18500,
    priceUnit: "FCFA / unité",
    minOrder: 1,
    inStock: true,
    badge: "Spécial Maraîchage",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6eb22509?auto=format&fit=crop&w=600&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1592417817098-8f3d6eb22509?auto=format&fit=crop&w=600&q=80",
    description: "Pulvérisateur haute résistance avec lance en laiton télescopique et buses interchangeables. Idéal pour les traitements phytosanitaires maraîchers et la désinfection de serres.",
    specs: ["Capacité : 16 Litres", "Lance en laiton robuste", "Pression : 2 à 4 bars régulée", "Bretelles ergonomiques rembourrées"],
  },
  {
    id: "PROD-10",
    name: "Kit d'Irrigation Goutte-à-Goutte Maraîcher (100m²)",
    domain: "agro",
    category: "agro-equipement",
    categoryLabel: "Équipements Agricoles & Matériels",
    price: 45000,
    priceUnit: "FCFA / kit complet",
    minOrder: 1,
    inStock: true,
    badge: "Économie d'Eau 70%",
    image: "https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&w=600&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&w=600&q=80",
    description: "Système complet d'arrosage goutte-à-goutte économique pour parcelles maraîchères de 100m². Goutteurs autorégulants évitant le gaspillage hydrique sous climat équatorial.",
    specs: ["Couverture : 100 m²", "Tuyaux goutteurs espacés de 20cm", "Raccords & vanne inclus", "Montage rapide sans outils"],
  },
  {
    id: "PROD-11",
    name: "Savon Noir Artisanal Saponifié à Froid (Pack 3x150g)",
    domain: "agro",
    category: "bio-cosmetique",
    categoryLabel: "Bio-Cosmétique & Artisanat",
    price: 3500,
    priceUnit: "FCFA / lot de 3 savons",
    minOrder: 1,
    inStock: true,
    badge: "100% Naturel & Surgras",
    image: "/images/savon-artisanal.jpg",
    fallbackImage: "/images/savon-artisanal.jpg",
    description: "Savon pur végétal saponifié à froid enrichi en beurre de karité et huile de palmiste locale. Nettoie en douceur sans dessécher la peau, biodégradable et respectueux de l'environnement.",
    specs: ["Poids : 3 pains de 150g", "Procédé : Saponification à froid", "Matières végétales congolaises", "Zéro colorant chimique"],
  },

  // ── DOMAINE SERVICES ──────────────────────────────────────
  {
    id: "PROD-12",
    name: "Pack Suivi Sanitaire & Zootechnique d'Élevage (Mensuel)",
    domain: "services",
    category: "audit-qhse",
    categoryLabel: "Services & Accompagnement",
    price: 50000,
    priceUnit: "FCFA / mois (visites incluses)",
    minOrder: 1,
    inStock: true,
    badge: "Encadrement Vétérinaire",
    image: "https://images.unsplash.com/photo-1441122456239-401e92b73c65?auto=format&fit=crop&w=600&q=80",
    fallbackImage: "https://images.unsplash.com/photo-1441122456239-401e92b73c65?auto=format&fit=crop&w=600&q=80",
    description: "Accompagnement terrain bimensuel par le Dr POUTYA sur votre exploitation : diagnostic sanitaire, ajustement des rations, autopsie préventive et protocole de biosécurité sur-mesure.",
    specs: ["2 visites physiques / mois à Pointe-Noire", "Ligne directe WhatsApp urgence", "Rapport zootechnique mensuel", "Réduction mortalité garantie"],
  },
  {
    id: "PROD-13",
    name: "Session Certifiante Conduite d'Élevage Avicole (Ferme-École)",
    domain: "services",
    category: "formations",
    categoryLabel: "Formations Professionnelles",
    price: 75000,
    priceUnit: "FCFA / apprenant (5 jours)",
    minOrder: 1,
    inStock: true,
    badge: "Certificat Officiel AVS",
    image: "/images/formation-ferme-ecole.jpg",
    fallbackImage: "/images/formation-ferme-ecole.jpg",
    description: "Formation 100% pratique en immersion ferme-école : maîtrise du démarrage des poussins, biosécurité, calcul des marges brutes et gestion sanitaire des bandes de poulets de chair.",
    specs: ["Durée : 5 jours (30h)", "Lieu : Ferme-école AVS Pointe-Noire", "Support pédagogique & matériel fournis", "Attestation certifiante remise"],
  },
]
