// lib/products.js
// Catalogue officiel des produits et intrants agropastoraux d'Agro Véto Services Congo

export const PRODUCT_CATEGORIES = [
  { id: 'all', label: 'Tous les Intrants' },
  { id: 'poussins', label: 'Poussins d\'un Jour' },
  { id: 'provenderie', label: 'Provenderie Certifiée' },
  { id: 'sante', label: 'Santé & Prophylaxie' },
  { id: 'hygiene', label: 'Hygiène & Biosécurité' },
  { id: 'materiel', label: 'Matériel & Équipements' },
]

export const PRODUCTS_CATALOG = [
  {
    id: "PROD-01",
    name: "Poussins d'un Jour Cobb 500 (Chair)",
    category: "poussins",
    categoryLabel: "Poussins & Reproduction",
    price: 650, // FCFA l'unité
    priceUnit: "FCFA / poussin (carton de 50)",
    minOrder: 50,
    inStock: true,
    badge: "⭐ Le Plus Rentable",
    image: "/images/products/poussins-cobb500.jpg",
    fallbackImage: "/images/products/poussins-cobb500.jpg",
    description: "Poussins d'un jour vigoureux, vaccinés Marek et Newcastle au couvoir. Taux de croissance exceptionnel et indice de conversion alimentaire optimal pour rentabiliser votre élevage de poulets de chair.",
    specs: ["Souche : Cobb 500", "Vaccination : Marek + Newcastle", "Conditionnement : Cartons aérés de 50 sujets", "Taux de viabilité > 98%"],
  },
  {
    id: "PROD-02",
    name: "Poussins Pondeuses Lohmann Brown",
    category: "poussins",
    categoryLabel: "Poussins & Reproduction",
    price: 950,
    priceUnit: "FCFA / sujet (carton de 50)",
    minOrder: 50,
    inStock: true,
    badge: "Ponte Élevée (320 œufs/an)",
    image: "/images/products/pondeuses-lohmann.jpg",
    fallbackImage: "/images/products/pondeuses-lohmann.jpg",
    description: "Poussins femelles de race pondeuse réputée pour sa robustesse tropicale et un pic de ponte prolongé avec une excellente coquille.",
    specs: ["Souche : Lohmann Brown", "Sexage : 99% garanti", "Entrée en ponte : 18-20 semaines", "Calibre d'œufs : Moyen à gros"],
  },
  {
    id: "PROD-03",
    name: "Aliment Volaille Démarrage Haute Énergie (50kg)",
    category: "provenderie",
    categoryLabel: "Provenderie Industrielle",
    price: 21500,
    priceUnit: "FCFA / sac 50kg",
    minOrder: 1,
    inStock: true,
    badge: "Formule Équilibrée",
    image: "/images/products/aliment-demarrage.jpg",
    fallbackImage: "/images/products/aliment-demarrage.jpg",
    description: "Formulation industrielle certifiée riche en protéines brutes (21%) et acides aminés essentiels pour un démarrage vigoureux et une ossature solide de J1 à J21.",
    specs: ["Protéines brutes : 21.5%", "Énergie métabolisable : 3050 kcal/kg", "Poids net : 50 kg", "Contrôlé en laboratoire AVS"],
  },
  {
    id: "PROD-04",
    name: "Aliment Volaille Croissance Performance (50kg)",
    category: "provenderie",
    categoryLabel: "Provenderie Industrielle",
    price: 19800,
    priceUnit: "FCFA / sac 50kg",
    minOrder: 1,
    inStock: true,
    badge: "Croissance Optimale",
    image: "/images/products/aliment-croissance.jpg",
    fallbackImage: "/images/products/aliment-croissance.jpg",
    description: "Aliment complet pour poulets de chair de J22 à J35. Maximise le gain moyen quotidien (GMQ) et optimise le ratio poids/aliment consommé.",
    specs: ["Protéines brutes : 19%", "Granulométrie : Miettes régulières", "Poids net : 50 kg", "Sans hormones ni farines interdites"],
  },
  {
    id: "PROD-05",
    name: "Aliment Volaille Finition & Engraissement (50kg)",
    category: "provenderie",
    categoryLabel: "Provenderie Industrielle",
    price: 18900,
    priceUnit: "FCFA / sac 50kg",
    minOrder: 1,
    inStock: true,
    badge: "Rendement Carcasse",
    image: "/images/products/aliment-finition.jpg",
    fallbackImage: "/images/products/aliment-finition.jpg",
    description: "Formule d'abattage à forte densité énergétique pour un beau persillage, une chair ferme et une saveur authentique sur le marché de Pointe-Noire.",
    specs: ["Protéines brutes : 18%", "Énergie : 3150 kcal/kg", "Poids net : 50 kg", "Période : De J36 à l'abattage"],
  },
  {
    id: "PROD-06",
    name: "Kit Prophylaxie Avicole Sanitaire Complète",
    category: "sante",
    categoryLabel: "Santé Animale & Soins",
    price: 16500,
    priceUnit: "FCFA / kit pour 100 sujets",
    minOrder: 1,
    inStock: true,
    badge: "Recommandé Vétérinaire",
    image: "/images/products/kit-prophylaxie.jpg",
    fallbackImage: "/images/products/kit-prophylaxie.jpg",
    description: "Ensemble tout-en-un comprenant vitamines antistress de démarrage, anticoccidien, antibiotique curatif préventif et calendrier de vaccination établi par le Dr POUTYA.",
    specs: ["Capacité : Traitement pour 100 poulets", "Guide d'administration inclus", "Validation vétérinaire AVS", "Date limite longue"],
  },
  {
    id: "PROD-07",
    name: "Désinfectant Virucide & Bactéricide Puissant (5L)",
    category: "hygiene",
    categoryLabel: "Biosécurité & Hygiène",
    price: 14500,
    priceUnit: "FCFA / bidon 5 litres",
    minOrder: 1,
    inStock: true,
    badge: "Norme HACCP",
    image: "/images/products/desinfectant-5l.jpg",
    fallbackImage: "/images/products/desinfectant-5l.jpg",
    description: "Solution concentrée pour la désinfection intégrale des poulaillers, pédiluves, rotoluves, cages et mangeoires. Efficace contre la grippe aviaire et la maladie de Newcastle.",
    specs: ["Volume : 5 Litres", "Dilution : 1% à 2%", "Spectre : Bactéricide, virucide, fongicide", "Agréé élevages professionnels"],
  },
  {
    id: "PROD-08",
    name: "Mangeoire Automatique Anti-Gaspillage (10kg)",
    category: "materiel",
    categoryLabel: "Équipements d'Élevage",
    price: 6500,
    priceUnit: "FCFA / unité",
    minOrder: 1,
    inStock: true,
    badge: "Plastique Renforcé",
    image: "/images/products/mangeoire-poules.jpg",
    fallbackImage: "/images/products/mangeoire-poules.jpg",
    description: "Mangeoire suspendue robuste avec grille anti-gaspillage intégrée. Réduit les pertes d'aliment de 25% et évite la souillure par les déjections.",
    specs: ["Capacité : 10 kg d'aliment", "Matériau : Plastique polypropylène haute densité", "Entretien : Lavable et désinfectable", "Usage : Chair et ponte"],
  },
]
